### ISSUE TITLE
Empty lines are not being ignored when parsing json with --job-params

### ISSUE THREAD

**Issue by imendes93** [lifebit-ai/cloudos-cli#3]
## Bug Description

When using the cloudOS package I ran into the following error:

> ValueError: Please, specify your parameters in test.config using the '=' char as spacer. E.g: name = my_name

The `test.config` contained an empty line, which caused the package to break. 

    params {
        csv = "s3://lifebit-featured-datasets/pipelines/pcgr/testdata/test_1/testdata.csv"
        metadata = "$baseDir/testdata/metadata.csv"
        genome = 'grch38'

        max_cpus = 2
        max_memory = 4.GB
    }

After removing this line, the problem was solved

## Expected behaviour

I would expect that empty lines in the config file to be ignored, not breaking the program. 

## Version tested

This was tested on a local installation of the following commit id
 
![image](https://user-images.githubusercontent.com/73831087/134345971-ec1fdb48-0e1a-4407-aa2d-c95ca45753a6.png)

**Comment by dapineyro** [comment]
Addressed in https://github.com/lifebit-ai/cloudos-cli/pull/53
