### ISSUE TITLE
Improve handling of SSL certificate verification for environments with specific network constraints

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/cloudos-cli#80]
## Overview of the issues

1. The package doesn't work out of the box in all versions for all our end users environments
2. The package in the edge version created for one of our end users organisation, is logging a lot of warnings that are confusing the end user, since warnings from a third part library are jointly emitted with our library's messages.

### Steps to reproduce

This is observed in the edge version `quay.io/lifebitaiorg/cloudos-py:v0.0.8bi` when executed in the respective environment.

```
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
```

When TLS/SSL verification is set to `False` the user experiences a lot of logging related to the recommendation of enforcing verification and it is difficult to understand if the command was executed successfully or if there is an error.

#### Command used 

```bash
cloudos job run     \
   --cloudos-url $CLOUDOS  \
   --apikey $MY_API_KEY     \
   --workspace-id $WORKSPACE_ID     \
   --project-name "$PROJECT_NAME"    \
   --job-name $JOB_NAME     \
   --workflow-name $WORKFLOW_NAME     \
   --nextflow-profile $NEXTFLOW_PROFILE   \
   --resumable   \
   --spot     \
   --batch
```

#### Command output

```console
CloudOS python package: a package for interacting with CloudOS.

CloudOS job functionality: run and check jobs in CloudOS.

Executing run...
/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is
 being made to host 'prod.cloudos.aws.com'. Adding certificate verification is strongly advised. See: https://ur
llib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is
 being made to host 'prod.cloudos.aws.com'. Adding certificate verification is strongly advised. See: https://ur
llib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is
 being made to host 'prod.cloudos.aws.com'. Adding certificate verification is strongly advised. See: https://ur
llib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
        Job successfully launched to CloudOS, please check the following link: https://prod.cloudos.aws.com/app/
jobs/630781f26d388a0149ecffb2
        Your assigned job id is: 630781f26d388a0149ecffb2
/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is
 being made to host 'prod.cloudos.aws.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
        Your current job status is: initializing
        To further check your job status you can either go to https://prod.cloudos.aws.com/app/jobs/630781f26d388a0149ecffb2 or use the following command:
cloudos job status \
    --apikey $MY_API_KEY \
    --cloudos-url https://prod.cloudos.aws.com \
    --job-id 630781f26d388a0149ecffb2
```

there are warnings that the user wouldn't need to view in a non-verbose mode

```console
/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is
 being made to host 'prod.cloudos.aws.com'. Adding certificate verification is strongly advised. See: https://ur
llib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is
 being made to host 'prod.cloudos.aws.com'. Adding certificate verification is strongly advised. See: https://ur
llib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is
 being made to host 'prod.cloudos.aws.com'. Adding certificate verification is strongly advised. See: https://ur
llib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
```
### a. Add global switch off flag for SSL verification as a flag `cloudos job run --verify false`
We should consider adding the verify ssl as a package metaflag and also introduce a verbosity level flag to allow the user to choose if they would like to see all the logs from dependencies or keep it clean to the `cloudos-cli` logs only, eg

```bash
cloudos job run --verify-certificates false --verbosity warn
cloudos job run --verify-certificates false --verbosity error
```

This could be achieved by using a context manager that monkey patches requests and changes it so that `verify=False` is the default and suppresses the warning (not recommended but possible).

Source: https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests

### b. Add global switch off flag for warnings from third party libraries 

Resources: 
-  Warning verbosity in `urllib3`: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings

### c. Add try/except handling to retry with no verification upon failure with `verify=True` (❌ mitm attacks vulnerability)

- Try/except if `verify=True` fails https://stackoverflow.com/a/65363043/10312089

Try/except would be a good approach that would ensure the package works out of the box for all our end users environments.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/38183826/186920708-0e28547e-29b2-4015-b50e-2f0447abe7b4.png">

<img width="796" alt="image" src="https://user-images.githubusercontent.com/38183826/186920682-396e9dd2-2c9e-4b71-acc2-c9dae6bcb743.png">

Note: This is bad practice since it leaves the library vulnerable for man-in-the-middle (MitM) attacks. Not recommended.

```
  #: SSL Verification default.
  #: Defaults to `True`, requiring requests to verify the TLS certificate at the
  #: remote end.
  #: If verify is set to `False`, requests will accept any TLS certificate
  #: presented by the server, and will ignore hostname mismatches and/or
  #: expired certificates, which will make your application vulnerable to
  #: man-in-the-middle (MitM) attacks.
  #: Only set this to `False` for testing.
  self.verify = True
```

### d. Allow the user to provide a path to the SSL certificates _(better practice ✅ )_

Source: https://www.geeksforgeeks.org/ssl-certificate-verification-python-requests/

Allow the user to provide the location of the ssl certificates (very common usecase with our end users in elevated security environments)

<img width="760" alt="Screenshot 2022-08-26 at 15 01 26" src="https://user-images.githubusercontent.com/38183826/186921203-a8ef0471-039d-433c-9a1b-21bf1dead289.png">

### e. Set these configurations persistently to reduce duplication

<img width="666" alt="image" src="https://user-images.githubusercontent.com/38183826/186923258-214bb375-6718-435f-a0c5-94639e252f42.png">

**Comment by dapineyro** [comment]
Implemented in https://github.com/lifebit-ai/cloudos-cli/pull/103
